# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: micheleroma92@gmail.com
author_name: KryptOs92
contract_name: turtle_eggs
deployment_language: python
preset_name: production
project_name: turtle-eggs

